apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: spring-boot-deployment
  template:
    metadata:
      labels:
        name: spring-boot-deployment
    spec:
      containers:
        - name: spring-boot
          image: usermanagement:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080